### ISSUE TITLE
Needs the spacex repo to actually make this run

### ISSUE THREAD

**Issue by abhi18av** [wilkerlucio/conj2018demo#1]
Hi @wilkerlucio,

I was  going through your presentations on YT for this repo and was curious about experimenting with this. However, it seems that this depends on another `spacex` repo which is local to your computer.

I'm not sure how to proceed in this situation 🤔

**Comment by wilkerlucio** [comment]
Hello, thanks, you are the first to notice it, hehe.

Sorry about that, I missed uploading, just did it now, you can find the code at: https://github.com/wilkerlucio/pathom-connect-spacex

**Comment by abhi18av** [comment]
Hehe, no worries. I'll be sticking around with `fulcro` and `pathom` so you can expect more issues and PRs to come along - hope you don't mind 😉

**Comment by wilkerlucio** [comment]
Not at all, keep it up! :)
